### ISSUE TITLE
Frontend App not initializing

### ISSUE THREAD

**Issue by ADK1x** [ninoseki/uzen#555]
Encountering the following errors in separate docker installs on a few machines:

```
worker_1    |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
worker_1    |     return future.result()
worker_1    |   File "/usr/local/lib/python3.9/site-packages/arq/worker.py", line 294, in main
worker_1    |     self._pool = await create_pool(
worker_1    |   File "/usr/local/lib/python3.9/site-packages/arq/connections.py", line 257, in create_pool
worker_1    |     return await create_pool(
worker_1    |   File "/usr/local/lib/python3.9/site-packages/arq/connections.py", line 257, in create_pool
worker_1    |     return await create_pool(
worker_1    |   File "/usr/local/lib/python3.9/site-packages/arq/connections.py", line 257, in create_pool
worker_1    |     return await create_pool(
worker_1    |   [Previous line repeated 2 more times]
worker_1    |   File "/usr/local/lib/python3.9/site-packages/arq/connections.py", line 230, in create_pool
worker_1    |     pool = await pool_factory(addr, db=settings.database, password=settings.password, encoding='utf8')
worker_1    |   File "/usr/local/lib/python3.9/site-packages/aioredis/pool.py", line 58, in create_pool
worker_1    |     await pool._fill_free(override_min=False)
worker_1    |   File "/usr/local/lib/python3.9/site-packages/aioredis/pool.py", line 383, in _fill_free
worker_1    |     conn = await self._create_new_connection(self._address)
worker_1    |   File "/usr/local/lib/python3.9/site-packages/aioredis/connection.py", line 111, in create_connection
worker_1    |     reader, writer = await asyncio.wait_for(open_connection(
worker_1    |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
worker_1    |     return fut.result()
worker_1    |   File "/usr/local/lib/python3.9/site-packages/aioredis/stream.py", line 23, in open_connection
worker_1    |     transport, _ = await get_event_loop().create_connection(
worker_1    |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1026, in create_connection
worker_1    |     infos = await self._ensure_resolved(
worker_1    |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1405, in _ensure_resolved
worker_1    |     return await loop.getaddrinfo(host, port, family=family, type=type,
worker_1    |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 861, in getaddrinfo
worker_1    |     return await self.run_in_executor(
worker_1    |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
worker_1    |     result = self.fn(*self.args, **self.kwargs)
worker_1    |   File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
worker_1    |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
worker_1    | socket.gaierror: [Errno -3] Temporary failure in name resolution

worker_1    | socket.gaierror: [Errno -2] Name or service not known
worker_1    | 11:18:38: redis connection error ('redis', 6379) gaierror [Errno -2] Name or service not known, 5 retries remaining...
worker_1    | 11:18:39: redis connection error ('redis', 6379) gaierror [Errno -2] Name or service not known, 4 retries remaining...
worker_1    | 11:18:40: redis connection error ('redis', 6379) gaierror [Errno -2] Name or service not known, 3 retries remaining...
worker_1    | 11:18:41: redis connection error ('redis', 6379) gaierror [Errno -2] Name or service not known, 2 retries remaining...
worker_1    | 11:18:42: redis connection error ('redis', 6379) gaierror [Errno -2] Name or service not known, 1 retries remaining...
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/lib/python3.9/site-packages/aioredis/stream.py", line 23, in open_connection
worker_1    |     transport, _ = await get_event_loop().create_connection(
worker_1    |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
worker_1    |     sock = await self._connect_sock(
worker_1    |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
worker_1    |     await self.sock_connect(sock, address)
worker_1    |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 499, in sock_connect
worker_1    |     return await fut
worker_1    | asyncio.exceptions.CancelledError
worker_1    | 
worker_1    | During handling of the above exception, another exception occurred:
worker_1    | 
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
worker_1    |     return fut.result()
worker_1    | asyncio.exceptions.CancelledError

uzen_app    |     conn = await self._create_new_connection(self._address)
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/aioredis/connection.py", line 111, in create_connection
uzen_app    |     reader, writer = await asyncio.wait_for(open_connection(
uzen_app    |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
uzen_app    |     return await fut
uzen_app    |   File "/usr/local/lib/python3.9/site-packages/aioredis/stream.py", line 23, in open_connection
uzen_app    |     transport, _ = await get_event_loop().create_connection(
uzen_app    |   File "uvloop/loop.pyx", line 1963, in create_connection
uzen_app    | socket.gaierror: [Errno -2] Name or service not known

uzen_app    | socket.gaierror: [Errno -2] Name or service not known
uzen_app    | 
uzen_app    | [2022-05-03 11:21:17 +0000] [9] [ERROR] Application startup failed. Exiting.
uzen_app    | [2022-05-03 11:21:17 +0000] [9] [INFO] Worker exiting (pid: 9)
uzen_app    | [2022-05-03 11:21:17 +0000] [7] [WARNING] Worker with pid 9 was terminated due to signal 15
uzen_app    | [2022-05-03 11:21:17 +0000] [7] [INFO] Shutting down: Master
uzen_app    | [2022-05-03 11:21:17 +0000] [7] [INFO] Reason: Worker failed to boot.

worker_2    | Traceback (most recent call last):
worker_2    |   File "/usr/local/bin/arq", line 8, in <module>
worker_2    |     sys.exit(cli())
worker_2    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in _call_
worker_2    |     return self.main(*args, **kwargs)
worker_2    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
worker_2    |     rv = self.invoke(ctx)
worker_2    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
worker_2    |     return ctx.invoke(self.callback, **ctx.params)
worker_2    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
worker_2    |     return __callback(*args, **kwargs)
worker_2    |   File "/usr/local/lib/python3.9/site-packages/arq/cli.py", line 48, in cli
worker_2    |     run_worker(worker_settings_, **kwargs)
worker_2    |   File "/usr/local/lib/python3.9/site-packages/arq/worker.py", line 756, in run_worker
worker_2    |     worker.run()
worker_2    |   File "/usr/local/lib/python3.9/site-packages/arq/worker.py", line 256, in run
worker_2    |     self.loop.run_until_complete(self.main_task)
worker_2    |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
worker_2    |     return future.result()
worker_2    |   File "/usr/local/lib/python3.9/site-packages/arq/worker.py", line 294, in main
worker_2    |     self._pool = await create_pool(
worker_2    |   File "/usr/local/lib/python3.9/site-packages/arq/connections.py", line 257, in create_pool
worker_2    |     return await create_pool(
worker_2    |   File "/usr/local/lib/python3.9/site-packages/arq/connections.py", line 257, in create_pool
worker_2    |     return await create_pool(
worker_2    |   File "/usr/local/lib/python3.9/site-packages/arq/connections.py", line 257, in create_pool
worker_2    |     return await create_pool(
worker_2    |   [Previous line repeated 2 more times]
worker_2    |   File "/usr/local/lib/python3.9/site-packages/arq/connections.py", line 230, in create_pool
worker_2    |     pool = await pool_factory(addr, db=settings.database, password=settings.password, encoding='utf8')
worker_2    |   File "/usr/local/lib/python3.9/site-packages/aioredis/pool.py", line 58, in create_pool
worker_2    |     await pool._fill_free(override_min=False)
worker_2    |   File "/usr/local/lib/python3.9/site-packages/aioredis/pool.py", line 383, in _fill_free
worker_2    |     conn = await self._create_new_connection(self._address)
worker_2    |   File "/usr/local/lib/python3.9/site-packages/aioredis/connection.py", line 111, in create_connection
worker_2    |     reader, writer = await asyncio.wait_for(open_connection(
worker_2    |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
worker_2    |     raise exceptions.TimeoutError() from exc
worker_2    | asyncio.exceptions.TimeoutError
```

**Comment by ninoseki** [comment]
I guess you do not run the Redis container. You can check whether the Redis container is running or not by the following  command.

```bash
$ docker compose up -d

$ docker ps --filter "name=uzen_redis"
CONTAINER ID   IMAGE               COMMAND                  CREATED         STATUS         PORTS                    NAMES
a1accb999290   bitnami/redis:6.2   "/opt/bitnami/script…"   2 minutes ago   Up 2 minutes   0.0.0.0:6379->6379/tcp   uzen_redis
```

If it is not running, something wrong with Docker compose. (but I don't have a clue to figure out)

**Comment by ADK1x** [comment]
> ```shell
> r "name=uzen_redis"
> ```

Yes, it fails to run and ends up in a restarting loop. This occurs on separate and different machines.

**Comment by ninoseki** [comment]
Again, I don't have a clue to fix the issue. Please re-review your Docker / Docker compose settings & environment.
